version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-p=dv9p3i7j$r!dw=8y(=igb(_+6w1i=8hsvt0w7ho1rn+pq!ti
    volumes:
      - .:/app
    ports:
      - "8000:8000"
